/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 */

import '@/global.css';

import { Platform } from 'react-native';

export const Colors = {
  light: {
    primary: '#006c49',
    onPrimary: '#ffffff',
    primaryContainer: '#10b981',
    onPrimaryContainer: '#00422b',
    primaryFixed: '#6ffbbe',
    primaryFixedDim: '#4edea3',
    onPrimaryFixed: '#002113',
    onPrimaryFixedVariant: '#005236',
    secondary: '#855300',
    onSecondary: '#ffffff',
    secondaryContainer: '#fea619',
    onSecondaryContainer: '#684000',
    secondaryFixed: '#ffddb8',
    secondaryFixedDim: '#ffb95f',
    onSecondaryFixed: '#2a1700',
    onSecondaryFixedVariant: '#653e00',
    tertiary: '#005ac2',
    onTertiary: '#ffffff',
    tertiaryContainer: '#71a1ff',
    onTertiaryContainer: '#00367a',
    tertiaryFixed: '#d8e2ff',
    tertiaryFixedDim: '#adc6ff',
    onTertiaryFixed: '#001a42',
    onTertiaryFixedVariant: '#004395',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    background: '#f8f9ff',
    onBackground: '#0b1c30',
    surface: '#f8f9ff',
    onSurface: '#0b1c30',
    surfaceVariant: '#d3e4fe',
    onSurfaceVariant: '#3c4a42',
    outline: '#6c7a71',
    outlineVariant: '#bbcabf',
    surfaceDim: '#cbdbf5',
    surfaceBright: '#f8f9ff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#eff4ff',
    surfaceContainer: '#e5eeff',
    surfaceContainerHigh: '#dce9ff',
    surfaceContainerHighest: '#d3e4fe',
    inverseSurface: '#213145',
    inverseOnSurface: '#eaf1ff',
    inversePrimary: '#4edea3',
    surfaceTint: '#006c49',
    // Compatibility with existing components
    text: '#0b1c30',
    textSecondary: '#3c4a42',
    backgroundElement: '#e5eeff',
    backgroundSelected: '#d3e4fe',
  },
  dark: {
    primary: '#4edea3',
    onPrimary: '#003924',
    primaryContainer: '#005236',
    onPrimaryContainer: '#6ffbbe',
    primaryFixed: '#6ffbbe',
    primaryFixedDim: '#4edea3',
    onPrimaryFixed: '#002113',
    onPrimaryFixedVariant: '#005236',
    secondary: '#ffb95f',
    onSecondary: '#462a00',
    secondaryContainer: '#653e00',
    onSecondaryContainer: '#ffddb8',
    secondaryFixed: '#ffddb8',
    secondaryFixedDim: '#ffb95f',
    onSecondaryFixed: '#2a1700',
    onSecondaryFixedVariant: '#653e00',
    tertiary: '#adc6ff',
    onTertiary: '#002e69',
    tertiaryContainer: '#004395',
    onTertiaryContainer: '#d8e2ff',
    tertiaryFixed: '#d8e2ff',
    tertiaryFixedDim: '#adc6ff',
    onTertiaryFixed: '#001a42',
    onTertiaryFixedVariant: '#004395',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    background: '#0b1c30',
    onBackground: '#e1e2e8',
    surface: '#0b1c30',
    onSurface: '#e1e2e8',
    surfaceVariant: '#404943',
    onSurfaceVariant: '#bfc9c1',
    outline: '#89938c',
    outlineVariant: '#404943',
    surfaceDim: '#0b1c30',
    surfaceBright: '#37474f',
    surfaceContainerLowest: '#081524',
    surfaceContainerLow: '#12202f',
    surfaceContainer: '#172535',
    surfaceContainerHigh: '#223040',
    surfaceContainerHighest: '#2d3b4b',
    inverseSurface: '#e1e2e8',
    inverseOnSurface: '#0b1c30',
    inversePrimary: '#006c49',
    surfaceTint: '#4edea3',
    // Compatibility with existing components
    text: '#ffffff',
    textSecondary: '#bfc9c1',
    backgroundElement: '#212225',
    backgroundSelected: '#2E3135',
  },
} as const;

export type ThemeColor = keyof typeof Colors.light & keyof typeof Colors.dark;

export const Fonts = Platform.select({
  ios: {
    sans: 'Inter',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'Inter',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: 'Inter, var(--font-display)',
    serif: 'var(--font-serif)',
    rounded: 'var(--font-rounded)',
    mono: 'var(--font-mono)',
  },
});

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  containerMargin: 16,
  stackGap: 16,
  sectionGap: 32,
} as const;

export const BorderRadius = {
  sm: 4,
  default: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 9999,
} as const;

export const BottomTabInset = Platform.select({ ios: 50, android: 80 }) ?? 0;
export const MaxContentWidth = 800;
